{
 "title": "Battery",
 "time": { "from": "2020-08-10T22:00:00.000Z", "to": "2020-08-12T00:00:00.000Z" },
 "panels": [
  {
   "title": "Transformer Loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Transformer Loading",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "EnergySystem",
     "select": [
      [
       { "params": [ "transformer1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "esdl_id",
       "operator": "=",
       "value": "e48ed4fa-6051-4bab-ba54-27c581be21a0"
      },
      { "condition": "AND", "key": "simulation_id", "operator": "=", "value": "workshop-test-78dc337e" }
     ]
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Battery State of Charge Home1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Battery",
     "select": [
      [
       { "params": [ "StateOfCharge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "esdl_id",
       "operator": "=",
       "value": "de40bae7-0ebe-4be8-9457-590a0657753e"
      },
      { "condition": "AND", "key": "simulation_id", "operator": "=", "value": "workshop-test-78dc337e" }
     ]
    },
    {
     "alias": "Battery State of Charge Home2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Battery",
     "select": [
      [
       { "params": [ "StateOfCharge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "esdl_id",
       "operator": "=",
       "value": "c17da550-37fc-4758-bef9-74fa717b8fa3"
      },
      { "condition": "AND", "key": "simulation_id", "operator": "=", "value": "workshop-test-78dc337e" }
     ]
    }
   ]
  },
  {
   "title": "PV Production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PV Active Power Production Home1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PVInstallation",
     "select": [
      [
       { "params": [ "current_pv_power_production" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "simulation_id", "operator": "=", "value": "workshop-test-78dc337e" },
      {
       "condition": "AND",
       "key": "esdl_id",
       "operator": "=",
       "value": "03443715-c345-45b2-9b95-bd6906ac9c83"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Power demand homes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active power Home1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ElectricityDemand",
     "select": [
      [
       { "params": [ "current_active_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "esdl_id",
       "operator": "=",
       "value": "25d212e5-ca5f-4a3d-9fb1-a5f024b2460a"
      },
      { "condition": "AND", "key": "simulation_id", "operator": "=", "value": "workshop-test-78dc337e" }
     ]
    },
    {
     "alias": "Active power Home2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ElectricityDemand",
     "select": [
      [
       { "params": [ "current_active_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "esdl_id",
       "operator": "=",
       "value": "8ccb0533-ea7f-4ef7-828b-f7909c099767"
      },
      { "condition": "AND", "key": "simulation_id", "operator": "=", "value": "workshop-test-78dc337e" }
     ]
    }
   ]
  }
 ]
}